### ISSUE TITLE
Harmony flag

### ISSUE THREAD

**Issue by Yomguithereal** [essence/essence.js#7]
Hello @felixgirault. Your library cannot function without the `--harmony` flag even with the latest versions of node. Maybe it would be nice to indicate it clearly in the documentation or even distribute on npm a built version that could work without the flag.

Thanks for your work on the library and have a good day.

**Comment by felixgirault** [comment]
Thank you for the notice, I added a note on the README.

I also tagged a version 3.0 with updated dependencies. Strangely, all tests passed on my machine but some are failing on Travis. If you are using the lib and you are willing to use the latest version, could you tell me if the tests are passing when you run them ?

**Comment by Yomguithereal** [comment]
Hello @felixgirault, I just clone the repo and ran the test and those seem to fail the same way they do on travis.

**Comment by Yomguithereal** [comment]
After investigating a little, some of your problems are coming from the passage from co v3 to co v4. The API has changed in a breaking way and seems to mess with your code.

**Comment by Yomguithereal** [comment]
I also tried to run the tests of v0.2.0 and they work flawlessly. There is definitely something wrong with the dependencies updates.

**Comment by felixgirault** [comment]
I was indeed very skeptical about the updates, I was surprised that everything passed given the breaking API changes... With a fresh install, the tests are failing like they should.
Thank you for your time, I'll probably release a 0.4.0 soon, hopefully not broken ^^
